### PR TITLE
Add support to Avalanche with BigQuery in Aave V3

### PR DESCRIPTION
**Pull request by marcellomaugeri**

### CODE REVIEW

**Comment by marcellomaugeri** [comment]
Not working. I'll get back once fixed

**Comment by marcellomaugeri** [comment]
Found the issue. The avalanche network on BigQuery is stuck at the 12th April 2024, but the code is working

**Review by 32ethers — APPROVED** [review]
Looks good, I will add the rest

**Comment by 32ethers** [comment]
> Found the issue. The avalanche network on BigQuery is stuck at the 12th April 2024, but the code is working

this seems worked

```
select * from bigquery-public-data.goog_blockchain_avalanche_contract_chain_us.logs where block_timestamp > "2024-12-1"
```

so it seems it's still working?

**Pull request merged**
